# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a795c6af17331a999ee386be8b7adfae273f82757e06b1107026a2731b4f853c55b5d3a4ed9c51e09f7de017d410cef29ea66cae21be41ef60add3afac82c6

test:
  secret_key_base: bd98e3aee9d5ecfea04d6c107f650c5ed2750f778c3938154717642bfd2438343f9a93d3d0b5734eaaaaada800f8decd57a7fc329941ab8fd5cd698aa44e2088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
